"""Browser acceptance against a running local development or production server.

Run: python tests/e2e.py --url http://127.0.0.1:5173
Requires Python Playwright and Chrome (or Playwright Chromium).
"""
import argparse
import json
import re
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

parser = argparse.ArgumentParser()
parser.add_argument('--url', default='http://127.0.0.1:5173')
args = parser.parse_args()
out = Path('test-results')
out.mkdir(exist_ok=True)
errors = []
checks = []

def check(name):
    checks.append(name)
    print('PASS', name, flush=True)

def choose(page, rule):
    page.goto(args.url, wait_until='domcontentloaded')
    page.locator(f'.rule-card.{rule} .rule-choose').click()

def prepare_card(page, rule, character_name):
    page.get_by_role('button', name='创建角色', exact=True).click()
    dialog = page.get_by_role('dialog')
    dialog.get_by_label('角色姓名').fill(character_name)
    dialog.locator('select').first.select_option('游侠' if rule == 'dnd' else '记者')
    if rule == 'dnd':
        dialog.get_by_label('职业等级').fill('')
        expect(dialog.get_by_label('职业等级')).to_have_value('1')
        dialog.get_by_label('种族').fill('半精灵')
    dialog.get_by_role('button', name='属性与状态', exact=True).click()
    dialog.get_by_label('力量属性').fill('')
    expect(dialog.get_by_label('力量属性')).to_have_value('1')
    dialog.get_by_role('button', name='重掷全部').click()
    dialog.get_by_role('button', name='重掷全部').click()
    if rule == 'dnd':
        dialog.get_by_label('生命上限').fill('12')
        dialog.get_by_label('当前生命').fill('12')
    else:
        con = int(dialog.get_by_label('体质属性').input_value())
        siz = int(dialog.get_by_label('体型属性').input_value())
        expect(dialog.get_by_label('生命上限')).to_have_value(str((con + siz)//10))
    dialog.get_by_role('button', name='技能与熟练', exact=True).click()
    if rule == 'dnd':
        dialog.get_by_role('button', name='建议分配', exact=True).click()
    else:
        dialog.get_by_label('信用评级职业点', exact=True).fill('9')
        dialog.get_by_label('侦查兴趣点', exact=True).fill('40')
    dialog.get_by_role('button', name='故事与行囊', exact=True).click()
    dialog.get_by_role('button', name='刷新词条').click()
    dialog.get_by_label('人物经历').fill('从雾港出发，寻找失踪的朋友。')
    dialog.get_by_role('button', name='物品', exact=True).click()
    dialog.get_by_label('物品1名称').fill('磨损的日记')
    dialog.get_by_label('物品1备注').fill('夹着一张旧码头的地图')
    with page.expect_download() as downloaded:
        dialog.get_by_role('button', name='JSON', exact=True).click()
    json_path = out / f'{rule}-character.json'
    downloaded.value.save_as(str(json_path))
    exported = json.loads(json_path.read_text())
    assert exported['name'] == character_name and exported['schemaVersion'] == 1
    with page.expect_download() as downloaded:
        dialog.get_by_role('button', name='Markdown', exact=True).click()
    md_path = out / f'{rule}-character.md'
    downloaded.value.save_as(str(md_path))
    assert '```json' in md_path.read_text()
    # The same exported Markdown must import through the actual browser input.
    dialog.locator('input[type=file]').set_input_files(str(md_path.resolve()))
    dialog.get_by_role('button', name='保存并提交审核').click()
    expect(page.get_by_role('dialog')).to_have_count(0)
    expect(page.locator('.my-character h3')).to_have_text(character_name)
    check(f'{rule}: create, reroll, skill setup, item, JSON/Markdown export and reimport')

def approve(host):
    host.get_by_role('button', name=re.compile('审核与制卡要求')).click()
    expect(host.get_by_role('button', name='通过此卡', exact=True)).to_be_enabled()
    host.get_by_role('button', name='通过此卡', exact=True).click()
    expect(host.get_by_role('button', name='已通过审核', exact=True)).to_be_disabled()
    host.get_by_role('button', name='关闭窗口').click()

def no_overflow(page, label):
    result = page.evaluate('({width:innerWidth, scroll:document.documentElement.scrollWidth})')
    assert result['scroll'] <= result['width'] + 1, (label, result)
    check(label + ': no horizontal overflow')

with sync_playwright() as p:
    chrome = Path('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome')
    browser = p.chromium.launch(headless=True, **({'executable_path': str(chrome)} if chrome.exists() else {}))
    host_context = browser.new_context(viewport={'width':1440,'height':1000}, accept_downloads=True)
    player_context = browser.new_context(viewport={'width':1440,'height':1000}, accept_downloads=True)
    host_context.set_default_timeout(8000)
    player_context.set_default_timeout(8000)
    host = host_context.new_page()
    player = player_context.new_page()
    for page in [host,player]:
        page.on('pageerror', lambda error: (errors.append(str(error)), print('BROWSER ERROR', str(error), flush=True)))
    host.goto(args.url, wait_until='domcontentloaded')
    expect(host.get_by_role('heading', name='好故事，从同桌开始。')).to_be_visible()
    host.screenshot(path=str(out/'01-welcome-light.png'), full_page=True, animations='disabled')
    host.get_by_role('button', name='切换深色模式').click()
    expect(host.locator('html')).to_have_attribute('data-theme','dark')
    host.screenshot(path=str(out/'02-welcome-dark.png'), full_page=True, animations='disabled')
    host.reload(wait_until='domcontentloaded')
    expect(host.locator('html')).to_have_attribute('data-theme','dark')
    host.get_by_role('button', name='切换浅色模式').click()
    check('Theme toggle and persistence')

    choose(host,'dnd')
    host.get_by_label('你的称呼').fill('林间 · DM')
    host.get_by_label('房间名称').fill('雾港来信')
    host.get_by_role('button',name='创建房间，成为主持人').click()
    expect(host.locator('.room-title h1')).to_have_text('雾港来信')
    code = host.locator('.room-code b').inner_text()
    expect(host.get_by_role('button',name='开启故事')).to_be_disabled()
    check('Host created real room; cannot start without players')

    choose(player,'coc')
    player.get_by_role('button',name='加入房间',exact=True).first.click()
    player.get_by_label('你的称呼').fill('阿鹿')
    player.get_by_label('房间码',exact=True).fill(code)
    player.locator('form').get_by_role('button',name='加入房间',exact=True).click()
    expect(player.get_by_role('alert')).to_contain_text('规则不匹配')
    player.get_by_role('button',name='返回选择规则').click()
    player.locator('.rule-card.dnd .rule-choose').click()
    player.get_by_role('button',name='加入房间',exact=True).first.click()
    player.get_by_label('房间码',exact=True).fill(code)
    player.locator('form').get_by_role('button',name='加入房间',exact=True).click()
    expect(player.locator('.room-title h1')).to_have_text('雾港来信')
    expect(host.locator('.member-row')).to_have_count(2)
    expect(player.get_by_role('button',name='我准备好了')).to_be_disabled()
    prepare_card(player,'dnd','埃兰 · 风行者')
    player.get_by_role('button',name='我准备好了').click()
    expect(host.get_by_role('button',name='开启故事')).to_be_disabled()
    host.get_by_role('button',name='我准备好了').click()
    expect(host.get_by_role('button',name='开启故事')).to_be_disabled()
    approve(host)
    expect(host.get_by_role('button',name='开启故事')).to_be_enabled()
    host.get_by_role('button',name='开启故事').click()
    expect(player.locator('.status-pill')).to_contain_text('故事进行中')
    expect(player.get_by_role('button',name='场景与回合',exact=True)).to_have_count(0)
    check('Rule mismatch rejected; readiness gate; host/player permissions')

    host.get_by_role('button',name='场景与回合',exact=True).click()
    host.get_by_label('场景名称').fill('第一幕 · 雾中的旧码头')
    host.get_by_label('场景描述').fill('潮水淹过木桩。远处，一盏本应熄灭的灯重新亮起。')
    host.get_by_role('button',name='公布场景').click()
    expect(host.get_by_role('dialog')).to_have_count(0)
    expect(player.locator('.current-scene')).to_contain_text('雾中的旧码头')
    host.get_by_label('公开叙事内容').fill('一个披着雨衣的人站在栈桥尽头，向你伸出一封被海水浸湿的信。')
    host.get_by_role('button',name='发送公开消息').click()
    expect(player.locator('.chat-text')).to_contain_text('被海水浸湿的信')
    player.get_by_label('公开叙事内容').fill('我握住弓，慢慢走向栈桥，观察那个人的手。')
    player.get_by_role('button',name='发送公开消息').click()
    expect(host.locator('.chat-text').last).to_contain_text('观察那个人的手')
    host.get_by_role('button',name='掷 D20',exact=True).click()
    expect(player.locator('.roll-event')).to_have_count(1)
    host.get_by_role('button',name='主持人暗骰',exact=True).click()
    host.get_by_label('自定义骰子表达式').fill('1d13+47')
    host.get_by_role('button',name='让骰子决定').click()
    expect(host.locator('.private-label')).to_have_count(1)
    expect(player.locator('.private-label')).to_have_count(0)
    expect(player.locator('.roll-event')).to_have_count(1)
    check('Scene and public chat synchronize; private roll hidden from player')

    player.get_by_role('button',name='检定',exact=True).click()
    player.get_by_role('button',name='优势',exact=True).click()
    player.get_by_role('button',name='进行检定').click()
    expect(player.locator('.roll-event')).to_have_count(2)
    player.get_by_role('button',name='行囊',exact=True).click()
    expect(player.locator('.inventory-item')).to_contain_text('磨损的日记')
    player.get_by_role('button',name='添加物品').click()
    player.get_by_label('物品名称',exact=True).fill('码头钥匙')
    player.get_by_role('button',name='放入行囊').click()
    expect(player.locator('.inventory-item')).to_have_count(2)
    player.get_by_role('button',name='减少生命',exact=True).click()
    expect(player.locator('.resource-control').first.locator('b')).to_have_text('11/12')
    player.reload(wait_until='domcontentloaded')
    expect(player.locator('.room-title h1')).to_have_text('雾港来信')
    expect(player.locator('.resource-control').first.locator('b')).to_have_text('11/12')
    expect(player.locator('.private-label')).to_have_count(0)
    expect(host.locator('.member-row')).to_have_count(2)
    check('DND check, inventory/resource update, authenticated refresh reconnect')

    host.get_by_role('button',name=re.compile('灵感小窗')).click()
    expect(host.get_by_text('Gemini 尚未连接',exact=True)).to_be_visible()
    expect(host.get_by_role('button',name='寻找一点灵感')).to_be_disabled()
    host.get_by_role('button',name='关闭窗口').click()
    check('AI unconfigured state is explicit; no fabricated response')
    host.screenshot(path=str(out/'03-room-light.png'),full_page=True, animations='disabled')
    host.get_by_role('button',name='切换深色模式').click()
    host.screenshot(path=str(out/'04-room-dark.png'),full_page=True, animations='disabled')
    no_overflow(host,'Desktop room 1440')

    for width in [390,320]:
        player.set_viewport_size({'width':width,'height':844})
        player.get_by_role('button',name='圆桌与记录').click()
        no_overflow(player,f'Mobile table {width}')
        player.screenshot(path=str(out/f'05-room-mobile-{width}.png'),full_page=True, animations='disabled')
        player.get_by_role('button',name='局内工具',exact=True).click()
        player.get_by_role('button',name='掷 D6',exact=True).click()
        no_overflow(player,f'Mobile dice {width}')
        player.screenshot(path=str(out/f'06-tools-mobile-{width}.png'),full_page=True, animations='disabled')
        player.get_by_role('button',name='同桌伙伴',exact=True).click()
        no_overflow(player,f'Mobile party {width}')
        player.get_by_role('button',name='查看角色卡').click()
        expect(player.get_by_role('dialog')).to_be_visible()
        no_overflow(player,f'Mobile character {width}')
        player.get_by_role('button',name='关闭窗口').click()
    player.set_viewport_size({'width':1440,'height':1000})
    host.get_by_role('button',name='返回准备',exact=True).click()
    host.get_by_role('button',name='场景与回合',exact=True).click()
    host.get_by_role('button',name='外部演绎',exact=True).click()
    host.get_by_role('button',name='关闭窗口').click()
    host.get_by_role('button',name='我准备好了').click()
    player.get_by_role('button',name='我准备好了').click()
    approve(host)
    host.get_by_role('button',name='开启故事').click()
    expect(player.get_by_label('公开叙事内容')).to_have_count(0)
    expect(player.locator('.external-mode-note')).to_be_visible()
    player.get_by_role('button',name='掷 D8',exact=True).click()
    check('External performance mode disables room chat but preserves tools')

    # Separate CoC room and complete a percentile workflow.
    coc_host = browser.new_context(viewport={'width':1440,'height':1000}).new_page()
    coc_player = browser.new_context(viewport={'width':1440,'height':1000},accept_downloads=True).new_page()
    for page in [coc_host,coc_player]:
        page.set_default_timeout(8000)
        page.on('pageerror',lambda error: errors.append(str(error)))
    choose(coc_host,'coc')
    coc_host.get_by_label('你的称呼').fill('阿夏 · KP')
    coc_host.get_by_label('房间名称').fill('钟声之后')
    coc_host.get_by_role('button',name='创建房间，成为主持人').click()
    expect(coc_host.locator('.room-title h1')).to_have_text('钟声之后')
    coc_code = coc_host.locator('.room-code b').inner_text()
    choose(coc_player,'coc')
    coc_player.get_by_role('button',name='加入房间',exact=True).first.click()
    coc_player.get_by_label('你的称呼').fill('雪莉')
    coc_player.get_by_label('房间码',exact=True).fill(coc_code)
    coc_player.locator('form').get_by_role('button',name='加入房间',exact=True).click()
    expect(coc_player.locator('.room-title h1')).to_have_text('钟声之后')
    prepare_card(coc_player,'coc','艾琳 · 洛温')
    coc_player.get_by_role('button',name='我准备好了').click()
    coc_host.get_by_role('button',name='我准备好了').click()
    approve(coc_host)
    coc_host.get_by_role('button',name='开启故事').click()
    coc_player.get_by_role('button',name='检定',exact=True).click()
    expect(coc_player.locator('.check-preview b')).to_have_text('65 / 32 / 13')
    coc_player.get_by_role('button',name='奖励骰',exact=True).click()
    coc_player.get_by_role('button',name='进行检定').click()
    expect(coc_host.locator('.roll-event')).to_have_count(1)
    coc_player.get_by_label('检定类型').select_option('sanity')
    expect(coc_player.get_by_role('button',name='奖励骰',exact=True)).to_have_count(0)
    expect(coc_player.locator('.check-preview b')).to_contain_text('D100 ≤')
    coc_player.get_by_role('button',name='进行检定').click()
    expect(coc_host.locator('.roll-event')).to_have_count(2)
    check('CoC skill thresholds, bonus dice and SAN checks synchronize')
    coc_player.screenshot(path=str(out/'07-coc-room.png'),full_page=True, animations='disabled')
    # Mobile standalone archive import/editor and malformed input validation.
    coc_player.set_viewport_size({'width':320,'height':844})
    coc_host.get_by_role('button',name='返回准备',exact=True).click()
    coc_player.get_by_role('button',name='同桌伙伴',exact=True).click()
    coc_player.get_by_role('button',name='编辑角色卡').click()
    expect(coc_player.get_by_role('button',name='导入',exact=True)).to_be_visible()
    coc_player.get_by_role('button',name='属性与状态',exact=True).click()
    no_overflow(coc_player,'Mobile CoC editor 320')
    coc_player.screenshot(path=str(out/'08-character-mobile-320.png'),full_page=True, animations='disabled')
    coc_player.get_by_role('dialog').locator('input[type=file]').set_input_files(str((out/'dnd-character.json').resolve()))
    expect(coc_player.get_by_role('dialog').get_by_role('alert')).to_contain_text('规则不匹配')
    check('Cross-rule character import rejected with an actionable error')
    coc_player.get_by_role('button',name='关闭窗口').click()
    # Fill the room to its supported capacity and inspect the seating at phone width.
    guests = []
    for number in range(3,9):
        guest = browser.new_context(viewport={'width':390,'height':844}).new_page()
        guest.set_default_timeout(8000)
        choose(guest,'coc')
        guest.get_by_role('button',name='加入房间',exact=True).first.click()
        guest.get_by_label('你的称呼').fill(f'同伴 {number}')
        guest.get_by_label('房间码',exact=True).fill(coc_code)
        guest.locator('form').get_by_role('button',name='加入房间',exact=True).click()
        expect(guest.locator('.room-title h1')).to_have_text('钟声之后')
        guests.append(guest)
    expect(coc_host.locator('.table-seat')).to_have_count(8)
    guests[-1].set_viewport_size({'width':320,'height':844})
    no_overflow(guests[-1],'Eight-seat table at 320')
    guests[-1].screenshot(path=str(out/'09-eight-seats-mobile.png'),full_page=True,animations='disabled')
    assert not errors, errors
    check('No browser runtime errors across all flows')
    browser.close()

(out/'acceptance.json').write_text(json.dumps({'checks':checks,'browserErrors':errors},ensure_ascii=False,indent=2))
print(f'Completed {len(checks)} browser checks.',flush=True)
