export const DND_ATTRIBUTES = [
  { key: 'str', label: '力量' },
  { key: 'dex', label: '敏捷' },
  { key: 'con', label: '体质' },
  { key: 'int', label: '智力' },
  { key: 'wis', label: '感知' },
  { key: 'cha', label: '魅力' },
];
export const COC_ATTRIBUTES = [
  { key: 'str', label: '力量' },
  { key: 'con', label: '体质' },
  { key: 'siz', label: '体型' },
  { key: 'dex', label: '敏捷' },
  { key: 'app', label: '外貌' },
  { key: 'int', label: '智力' },
  { key: 'pow', label: '意志' },
  { key: 'edu', label: '教育' },
  { key: 'luck', label: '幸运' },
];
export const DND_SKILLS = [
  { key: 'acrobatics', label: '体操', attribute: 'dex' },
  { key: 'animalHandling', label: '驯兽', attribute: 'wis' },
  { key: 'arcana', label: '奥秘', attribute: 'int' },
  { key: 'athletics', label: '运动', attribute: 'str' },
  { key: 'deception', label: '欺瞒', attribute: 'cha' },
  { key: 'history', label: '历史', attribute: 'int' },
  { key: 'insight', label: '洞悉', attribute: 'wis' },
  { key: 'intimidation', label: '威吓', attribute: 'cha' },
  { key: 'investigation', label: '调查', attribute: 'int' },
  { key: 'medicine', label: '医药', attribute: 'wis' },
  { key: 'nature', label: '自然', attribute: 'int' },
  { key: 'perception', label: '察觉', attribute: 'wis' },
  { key: 'performance', label: '表演', attribute: 'cha' },
  { key: 'persuasion', label: '游说', attribute: 'cha' },
  { key: 'religion', label: '宗教', attribute: 'int' },
  { key: 'sleightOfHand', label: '巧手', attribute: 'dex' },
  { key: 'stealth', label: '隐匿', attribute: 'dex' },
  { key: 'survival', label: '求生', attribute: 'wis' },
];
/** Dodge and own language use DEX/2 and EDU at character creation. */
export const COC_SKILLS = [
  { key: 'accounting', label: '会计', base: 5 },
  { key: 'anthropology', label: '人类学', base: 1 },
  { key: 'appraise', label: '估价', base: 5 },
  { key: 'archaeology', label: '考古学', base: 1 },
  { key: 'artCraft', label: '艺术／手艺', base: 5 },
  { key: 'artLiterature', label: '艺术／文学', base: 5 },
  { key: 'artPhotography', label: '艺术／摄影', base: 5 },
  { key: 'artActing', label: '艺术／表演', base: 5 },
  { key: 'scienceBiology', label: '科学／生物学', base: 1 },
  { key: 'sciencePharmacy', label: '科学／药学', base: 1 },
  { key: 'languageLatin', label: '外语／拉丁语', base: 1 },
  { key: 'charm', label: '魅惑', base: 15 },
  { key: 'climb', label: '攀爬', base: 20 },
  { key: 'creditRating', label: '信用评级', base: 0 },
  { key: 'cthulhuMythos', label: '克苏鲁神话', base: 0 },
  { key: 'disguise', label: '乔装', base: 5 },
  { key: 'dodge', label: '闪避', base: 0 },
  { key: 'driveAuto', label: '汽车驾驶', base: 20 },
  { key: 'electricalRepair', label: '电气维修', base: 10 },
  { key: 'fastTalk', label: '话术', base: 5 },
  { key: 'fightingBrawl', label: '斗殴', base: 25 },
  { key: 'firearmsHandgun', label: '手枪', base: 20 },
  { key: 'firearmsRifle', label: '步枪／霰弹枪', base: 25 },
  { key: 'firstAid', label: '急救', base: 30 },
  { key: 'history', label: '历史', base: 5 },
  { key: 'intimidate', label: '恐吓', base: 15 },
  { key: 'jump', label: '跳跃', base: 20 },
  { key: 'law', label: '法律', base: 5 },
  { key: 'libraryUse', label: '图书馆使用', base: 20 },
  { key: 'listen', label: '聆听', base: 20 },
  { key: 'locksmith', label: '锁匠', base: 1 },
  { key: 'mechanicalRepair', label: '机械维修', base: 10 },
  { key: 'medicine', label: '医学', base: 1 },
  { key: 'naturalWorld', label: '博物学', base: 10 },
  { key: 'navigate', label: '领航', base: 10 },
  { key: 'occult', label: '神秘学', base: 5 },
  { key: 'otherLanguage', label: '外语', base: 1 },
  { key: 'ownLanguage', label: '母语', base: 0 },
  { key: 'persuade', label: '说服', base: 10 },
  { key: 'pilot', label: '驾驶（飞行器）', base: 1 },
  { key: 'psychoanalysis', label: '精神分析', base: 1 },
  { key: 'psychology', label: '心理学', base: 10 },
  { key: 'ride', label: '骑术', base: 5 },
  { key: 'science', label: '科学', base: 1 },
  { key: 'sleightOfHand', label: '妙手', base: 10 },
  { key: 'spotHidden', label: '侦查', base: 25 },
  { key: 'stealth', label: '潜行', base: 20 },
  { key: 'survival', label: '生存', base: 10 },
  { key: 'swim', label: '游泳', base: 20 },
  { key: 'throw', label: '投掷', base: 20 },
  { key: 'track', label: '追踪', base: 10 },
];
export const DND_CLASSES = [
  '野蛮人',
  '吟游诗人',
  '牧师',
  '德鲁伊',
  '战士',
  '武僧',
  '圣武士',
  '游侠',
  '游荡者',
  '术士',
  '邪术师',
  '法师',
];
export const DND_ANCESTRIES = [
  '人类',
  '矮人',
  '精灵',
  '半身人',
  '龙裔',
  '侏儒',
  '半精灵',
  '半兽人',
  '提夫林',
];
export const COC_OCCUPATIONS = [
  '古物学家',
  '作家',
  '记者',
  '私家侦探',
  '医生',
  '教授',
  '警探',
  '艺术家',
  '神职人员',
  '军人',
  '考古学家',
];
